name: Verify Code
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Verify Dependencies
        run: go mod verify
      - name: Run Tests
        run: go test -race -coverprofile=coverage.out ./... > coverageout.txt
      - name: Coverage Results
        if: github.event_name != "pull_request"
        run: cat coverageout.txt
      - name: Write Coverage File
        if: github.event_name == "pull_request"
        run: go tool cover -html coverage.out -html coverageout.html
      - name: Commenting To PR
        if: github.event_name == "pull_request"
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: coverageout.txt
