name: Verify Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get
      - name: Run Build
        run: go build ./...
      - name: Run Vet & Lint
        run: | 
          go vet ./...
          golint ./...
      - name: Run Tests
        run: go test -v ./...
